### ISSUE TITLE
Cant get app to work

### ISSUE THREAD

**Issue by macjeff** [dkirker/smartthings-lockitron#2]
Got my secret and ID and put it all in there but touch app and nothing happens.

What am I missing?

**Comment by macjeff** [comment]
Update.  Maybe their website was down but now I get an authentication screen.  I enter my data and it logs in but then I get an error occurred- possibly bad authentication type

**Comment by macjeff** [comment]
i am getting this now....I login and it asks me to authenticate (thats after entering all the client ID and client secret in app settings)   

{"error":true,"type":"AccessDenied","message":"This request is not authorized by the specified access token"}

**Comment by dkirker** [comment]
Hey, sorry for not responding sooner. I haven't touched Lockitron in some time. I'm not sure what I can promise with this, but I might be able to get a look.

**Comment by bob5731** [comment]
how do I set ti up?

**Comment by botondszaktilla** [comment]
Any chance for an update dkirk?
